package com.udit.bankexam.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.support.annotation.IntDef;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table "FAVORITE_RECORD".
 */
@Entity
public class FavoriteRecord {
   /* @Id(autoincrement = true)
    private Long _id;*/
    //@Property(nameInDb = "ID")
    @Id(autoincrement = false)
    private String ID;
    @Property(nameInDb = "Ftype")
    private String FType;
    @Property(nameInDb = "FDate")
    private String FDate;
    @Property(nameInDb = "LinkID")
    private String LinkID;
    @Property(nameInDb = "UID")
    private String UID;



    @Generated(hash = 1570331990)
    public FavoriteRecord(String ID, String FType, String FDate, String LinkID, String UID) {
        this.ID = ID;
        this.FType = FType;
        this.FDate = FDate;
        this.LinkID = LinkID;
        this.UID = UID;
    }

    @Generated(hash = 1447135516)
    public FavoriteRecord() {
    }



    public void setID(String ID) {
        this.ID = ID;
    }

    public String getFType() {
        return FType;
    }

    public void setFType(String FType) {
        this.FType = FType;
    }

    public String getFDate() {
        return FDate;
    }

    public void setFDate(String FDate) {
        this.FDate = FDate;
    }

    public String getLinkID() {
        return LinkID;
    }

    public void setLinkID(String LinkID) {
        this.LinkID = LinkID;
    }

    public String getUID() {
        return UID;
    }

    public void setUID(String UID) {
        this.UID = UID;
    }

    public String getID() {
        return this.ID;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        FavoriteRecord record = (FavoriteRecord) o;

        if (FType != null ? !FType.equals(record.FType) : record.FType != null) return false;
        if (LinkID != null ? !LinkID.equals(record.LinkID) : record.LinkID != null) return false;
        return UID != null ? UID.equals(record.UID) : record.UID == null;

    }

    @Override
    public int hashCode() {
        int result = FType != null ? FType.hashCode() : 0;
        result = 31 * result + (LinkID != null ? LinkID.hashCode() : 0);
        result = 31 * result + (UID != null ? UID.hashCode() : 0);
        return result;
    }
}
