package com.udit.bankexam.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.udit.bankexam.bean.FavoriteRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FAVORITE_RECORD".
*/
public class FavoriteRecordDao extends AbstractDao<FavoriteRecord, String> {

    public static final String TABLENAME = "FAVORITE_RECORD";

    /**
     * Properties of entity FavoriteRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, String.class, "ID", true, "ID");
        public final static Property FType = new Property(1, String.class, "FType", false, "Ftype");
        public final static Property FDate = new Property(2, String.class, "FDate", false, "FDate");
        public final static Property LinkID = new Property(3, String.class, "LinkID", false, "LinkID");
        public final static Property UID = new Property(4, String.class, "UID", false, "UID");
    }


    public FavoriteRecordDao(DaoConfig config) {
        super(config);
    }
    
    public FavoriteRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FAVORITE_RECORD\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: ID
                "\"Ftype\" TEXT," + // 1: FType
                "\"FDate\" TEXT," + // 2: FDate
                "\"LinkID\" TEXT," + // 3: LinkID
                "\"UID\" TEXT);"); // 4: UID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FAVORITE_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FavoriteRecord entity) {
        stmt.clearBindings();
 
        String ID = entity.getID();
        if (ID != null) {
            stmt.bindString(1, ID);
        }
 
        String FType = entity.getFType();
        if (FType != null) {
            stmt.bindString(2, FType);
        }
 
        String FDate = entity.getFDate();
        if (FDate != null) {
            stmt.bindString(3, FDate);
        }
 
        String LinkID = entity.getLinkID();
        if (LinkID != null) {
            stmt.bindString(4, LinkID);
        }
 
        String UID = entity.getUID();
        if (UID != null) {
            stmt.bindString(5, UID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FavoriteRecord entity) {
        stmt.clearBindings();
 
        String ID = entity.getID();
        if (ID != null) {
            stmt.bindString(1, ID);
        }
 
        String FType = entity.getFType();
        if (FType != null) {
            stmt.bindString(2, FType);
        }
 
        String FDate = entity.getFDate();
        if (FDate != null) {
            stmt.bindString(3, FDate);
        }
 
        String LinkID = entity.getLinkID();
        if (LinkID != null) {
            stmt.bindString(4, LinkID);
        }
 
        String UID = entity.getUID();
        if (UID != null) {
            stmt.bindString(5, UID);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public FavoriteRecord readEntity(Cursor cursor, int offset) {
        FavoriteRecord entity = new FavoriteRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // ID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // FType
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // FDate
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // LinkID
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // UID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FavoriteRecord entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setFType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLinkID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUID(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final String updateKeyAfterInsert(FavoriteRecord entity, long rowId) {
        return entity.getID();
    }
    
    @Override
    public String getKey(FavoriteRecord entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FavoriteRecord entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
